### ISSUE TITLE
Feature request: ability to add secrets to organizations and repositories

### ISSUE THREAD

**Issue by richard-grainger-veeva** [aws-ia/cloudformation-github-resource-providers#18]
It would be useful to be able to add secrets to orgs and repos:

- https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#create-or-update-a-repository-secret
- https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#create-or-update-an-organization-secret

Thanks!

**Comment by CloudChoom** [comment]
@richard-grainger-veeva Many thanks for the feedback! I'm a product manager at AWS on the CloudFormation team, our team is looking into this request.

In the meantime, would you be open to a quick chat about your use cases and other 3rd party resource types that would be helpful for us to support? If so, feel free to [contact me on LinkedIn](https://www.linkedin.com/in/lucasqchen).

**Comment by lukiwlosek** [comment]
PR which adds this feature **https://github.com/aws-ia/cloudformation-github-resource-providers/pull/21**

**Comment by ericzbeard** [comment]
I'll work on getting this incorporated into the publishing pipeline.

**Comment by ericzbeard** [comment]
@lukiwlosek are you interested in contributing to the release pipeline? The CICD template is here: https://github.com/aws-cloudformation/community-registry-extensions/blob/main/release/github/cicd.yml

It would involve making a few changes on this side as well, to add an integ template, and modify the inputs so that we can automate things using parameter store. You can look into the existing resources here to see how we do that using the `setup.sh` script (Example here: https://github.com/aws-ia/cloudformation-github-resource-providers/blob/main/GitHub-Git-Tag/setup.sh)

**Comment by lukiwlosek** [comment]
@ericzbeard I have added a PR for the pipeline script and left some comments: https://github.com/aws-cloudformation/community-registry-extensions/pull/137, 

Also created a PR for the resource script as well: https://github.com/aws-ia/cloudformation-github-resource-providers/pull/22

**Comment by ericzbeard** [comment]
I requested one small change to 137.
